### Admin Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@sendit.com",
  "password": "Admin@1234"
}


#### Register a New User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "phone": "0712345678",
  "password": "password123"
}

###

### Login as a User or Driver
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}

###

### Create Driver (Admin Only)
POST http://localhost:3000/api/auth/create-driver
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5Ac2VuZGl0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MzIyMDYwMSwiZXhwIjoxNzUzODI1NDAxfQ.e-JzUe581YmuuyOAJN6CD3snnPl7l2ecCA_sY6nJOiU

{
  "name": "Rider One",
  "email": "driver1@example.com",
  "password": "driverpassword",
  "mode": "MOTORCYCLE"
}

###

### Login as Driver
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "driver1@example.com",
  "password": "driverpassword"
}
